version: "3.9"
services:
  mongodb:
    image: mongo:6.0
    ports:
      - 27017:27017
    volumes:
      - ./scripts/mongodb_init.sh:/docker-entrypoint-initdb.d/mongodb_init.sh
    healthcheck:
      test:
        [
          "CMD",
          "echo",
          "'db.runCommand({serverStatus:1}).ok'",
          "|",
          "mongo admin",
          "-u $MONGO_INITDB_ROOT_USERNAME",
          "-p $MONGO_INITDB_ROOT_PASSWORD",
          "--quiet | grep 1",
        ]
      interval: 1s
      timeout: 10s
      retries: 3
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_INITDB_ROOT_PASSWORD
      - MONGO_USER=$MONGO_USER
      - MONGO_USER_PASSWORD=$MONGO_USER_PASSWORD
      - MONGO_USER_ROLE=$MONGO_USER_ROLE
    container_name: archant_mongodb
    restart: unless-stopped

networks:
  default:
    name: archant_net
